services:
  hub:
    image: selenium/hub:4.20
  chrome:
    image: selenium/node-chrome:4.20
    depends_on: 
      - hub
    shm_size: '2g'
    env_file: .env
    deploy:
      replicas: 1
  firefox:
    image: selenium/node-firefox:4.20
    depends_on: 
      - hub
    shm_size: '2g'
    deploy:
      replicas: 1
    env_file: .env